name: Main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - run: zig fmt --check src/*.zig test/*.zig

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - run: zig build test
